### PR TITLE
add Windows statics

### PR DESCRIPTION
**Pull request by Gorillq**
On linux works flawless, I added Windows solution, but on my machine it shows username@hostname correctly, however colors doesn't work anymore. I cross-compiled it so maybe that's a reason. Have to be revieved and  eventually corrected

### CODE REVIEW

**Comment by deepesh611** [comment]
I did run the code in Powershell and wsl. It works perfectly, as well as the color codes

**Comment by deepesh611** [comment]
Also, i have made some changes in the main branch, pls do fork the new code.
And also, there is a variable for your <ROOT_PATH>, its also static

**Comment by deepesh611** [comment]
rn, i m having merge conflicts with you code, so for now, I'll be rejecting this pr.

**Comment by Gorillq** [comment]
sorry I commited before pull, I'm closing it and send you correct one soon if you like :)

**Comment by deepesh611** [comment]
> sorry I commited before pull, I'm closing it and send you correct one soon if you like :)

Cool
and no need for sorrys n stuff 👍

**Pull request closed without merging**
